apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: fakeshop
  namespace: default
spec:
  selector:
    app: fakeshop
  type: LoadBalancer
  ports:
  - name: fakeshop
    protocol: TCP
    port: 5000
    targetPort: 5000


